---
- name: Install Standalone ceilometer
  hosts: local
  vars:
    mysql_root_password: "password"
  sudo: yes
  tasks:
  # Adding cloud repo and update,upgrade
  - name: Install Cloud keyring
    apt: name=ubuntu-cloud-keyring state=present
  - name: Adding package to repository list
    shell: echo "deb http://ubuntu-cloud.archive.canonical.com/ubuntu" "trusty-updates/kilo main" > /etc/apt/sources.list.d/cloudarchive-kilo.list
  - name: apt update
    apt: update_cache=yes
  - name: apt dist-upgrade
    apt: upgrade=dist

 #Installing Mysql Service
  - name: Install Mysql Service
    apt: name={{ item }} state=installed update_cache=yes
    with_items:
      - mariadb-server
      - python-mysqldb

  - name: Copy cnf file 
    template: src=mysqld_openstack.cnf.j2 dest=/etc/mysql/conf.d/mysqld_openstack.cnf owner=root group=root mode=0644 
  - name: Start the MySQL service
    service: name=mysql state=restarted enabled=true

  # Mysql secure installation
  # Note: Please comment this section if this playbook is not excuting first time(fix me)
  - name: delete anonymous MySQL server user for localhost
    action: mysql_user user="" host="localhost" state="absent" 
  - name: delete anonymous MySQL server user for localhost
    action: mysql_user user="" state="absent" 
  - name: remove the MySQL test database
    action: mysql_db db=test state=absent
 
  #Updating root permissions
  - name: update mysql root password for all root accounts
    sudo: yes
    mysql_user: 
      name: root 
      host: "{{ item }}" 
      login_user: root
      #password: "{{ mysql_root_password }}"
      password: "password"
      login_password: "{{ mysql_root_password }}"
      check_implicit_admin: yes
      priv: "*.*:ALL,GRANT"
    with_items:
      - "{{ ansible_hostname }}"
      - 127.0.0.1
      - ::1
      - localhost

  #Installing rabbitmq service
  - name: rabbitmq-server
    apt: name=rabbitmq-server state=present
  - name : Adding Rabbitmq user
    shell : rabbitmqctl add_user openstack "password";rabbitmqctl set_permissions openstack ".*" ".*" ".*"

  # Installing Keystone Service
  - name: Creating keystone.override file 
    template: src=keystone.override.j2 dest=/etc/init/keystone.override owner=root group=root mode=0644 

  - name: Install Keystone
    apt: name={{ item }} state=installed update_cache=yes
    with_items:
      - keystone 
      - python-openstackclient 
      - apache2 
      - libapache2-mod-wsgi 
      - memcached 
      - python-memcache
      - curl
  #Creating keystone database
  - name: Keystone create DB for service
    mysql_db:
      login_user: "root"
      login_password: "password"
      login_host: "localhost"
      name: "keystone"
      state: "present"
  - name: Keystone grant access to the DB for the service
    mysql_user:
      login_user: "root"
      login_password: "password"
      login_host: "localhost"
      name: "keystone"
      password: "password"
      host: "{{ item }}"
      state: "present"
      priv: "keystone.*:ALL"
    with_items:
       - "localhost"
       - "%"
  - name: Creating keystone.conf  
    template: src=keystone.conf.j2 dest=/etc/keystone/keystone.conf owner=root group=root mode=0644
  - name: Running sync database
    shell: /bin/sh -c "keystone-manage db_sync" keystone
 
  # Configuring apache server
  - name: Adding new line
    lineinfile: dest=/etc/apache2/apache2.conf line="ServerName localhost"

  - name: Creating wsgi keystone.conf  
    template: src=wsgi-keystone.conf.j2 dest=/etc/apache2/sites-available/wsgi-keystone.conf owner=root group=root mode=0644
#  - name : Configuring keystone
#    script: keystone_setup.sh
  - name: soft linkt to keystons wsgi
    command: ln -s /etc/apache2/sites-available/wsgi-keystone.conf /etc/apache2/sites-enabled
    ignore_errors: yes
  - name: creating cgi bin dir
    command: mkdir -p /var/www/cgi-bin/keystone
  - name: copying keystone.py as main file
    template: src=main.j2 dest=/var/www/cgi-bin/keystone/main owner=root group=root mode=0644
  - name: copying keystone.py as admin file
    template: src=admin.j2 dest=/var/www/cgi-bin/keystone/admin owner=root group=root mode=0644
  - name: Restart apache2 service
    service: name=apache2 state=restarted enabled=true


  #Installing mongod db server
  - name: Install the Mongo db server
    apt: name={{ item }} state=installed update_cache=yes
    with_items:
      - mongodb-server
      - mongodb-clients
      - python-pymongo
  - name: Creating mongodb.conf
    template: src=mongodb.conf.j2 dest=/etc/mongodb.conf owner=root group=root mode=0644
  - name: Start the Mongodb service
    service: name=mongodb state=restarted enabled=true
  - name: Stopping mongodb service
    service: name=mongodb state=stopped
  - name: Removing mongodb files
    shell: rm -rf /var/lib/mongodb/journal/prealloc.*
  - name: Restarting mongodb service
    service: name=mongodb state=restarted

  - name : Configuring users
    script: configure_users_roles.sh
  - name: Adding ceilometer database
    mongodb_user: database=ceilometer name=ceilometer password=password roles='readWrite,userAdmin' state=present

  #Installing Ceilometer Services
  - name : Install Ceilometer services
    apt: name={{ item }} state=installed update_cache=yes
    with_items:
      - ceilometer-api
      - ceilometer-collector
      - ceilometer-agent-central
      - ceilometer-agent-notification
      - ceilometer-alarm-evaluator
      - ceilometer-alarm-notifier
      - python-ceilometerclient
  - name: Creating Ceilometer.conf
    template: src=ceilometer.conf.j2 dest=/etc/ceilometer/ceilometer.conf owner=root group=root mode=0644

  - name: Retarting Celometer API
    service: name=ceilometer-api state=restarted

  - name: Retarting ceilometer-agent-central
    service: name=ceilometer-agent-central state=restarted

  - name: Retarting ceilometer-agent-notification
    service: name=ceilometer-agent-notification state=restarted

  - name: Retarting ceilometer-alarm-evaluator
    service: name=ceilometer-alarm-evaluator state=restarted

  - name: Retarting ceilometer-alarm-notifier
    service: name=ceilometer-alarm-notifier state=restarted

